### ISSUE TITLE
Raise test timeout

### ISSUE THREAD

**Issue by nh2** [jensblanck/cdar#7]
In

https://github.com/jensblanck/cdar/blob/f7e6b6bfb296a89232b0555425f698accb98264b/test/Test.hs#L24

the test timeout is set to 200 ms. That breaks running the tests on massively parallel CI servers, such as the one I run for [static-haskell-nix](https://github.com/nh2/static-haskell-nix), where the process may not be scheduled for a while.

It would be great if the timeout could be raised to make that unlikely, or if one could give an option to set it from the CLI or disable the timeout entirely.

**Comment by jensblanck** [comment]
Hi, I'm a newbie with regards to project maintenance. I'd be happy to change to whatever value you wish, or if you could tell me how to disable the limit.

**Comment by nh2** [comment]
@jensblanck I'll just do a semi-educated guess and that 10x the current value (2 seconds) will probably be fine on most very-busy machines.

You're apparently using [`tasty`](https://github.com/UnkindPartition/tasty); that seems to have a [CLI option](https://github.com/UnkindPartition/tasty#runtime) `--timeout`. If you could find out which one takes precedence if that's given (that value, or your `mkTimeout` value in the code above), and it turns out that it's that value, that would also provide a nice way to override it externally.

Thanks!

**Comment by jensblanck** [comment]
Changed to 4 seconds.

**Comment by nh2** [comment]
Thanks!
